name: CI workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      
      # Linting with flake8
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      
      # Run unit tests with nose
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      
      # Security scanning with Bandit
      - name: Security Scanning with Bandit
        run: |
          bandit -r src
      
      # Upload coverage report to Codecov
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      # Notification on failure
      - name: Notify on failure
        if: failure()
        run: |
          # Send notification here (e.g., Slack, email)
